apiVersion: v1
kind: Service
metadata:
  name: chatserver-service
spec:
  type: ClusterIP
  selector:
    app: ChatServer
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001